set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smarttab
syntax on
set autoindent
set hlsearch
set incsearch
set nu
set backspace=indent,eol,start
execute pathogen#infect()
let g:nerdtree_tabs_open_on_console_startup=1
