set tabstop=2
set shiftwidth=2
set softtabstop=2
set smarttab
syntax on
set autoindent
set hlsearch
set incsearch
set nu
set backspace=indent,eol,start
set exrc
set secure
execute pathogen#infect()
let g:nerdtree_tabs_open_on_console_startup=1

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set nosmarttab
